var argv = require('yargs').argv;
var path = require('path');

module.exports = function(config) {
  config.set({
    browsers:["PhantomJS"],
    singleRun:!argv.watch,
    frameworks:['mocha','chai'],
    reporters:['spec'],
    files:[
      'node_modules/babel-polyfill/dist/polyfill.js',
      'node_modules/phantomjs-polyfill/bind-polyfill.js',
      './test/**/*.js'
    ],
    preprocessors:{
       ['./test/**/*.js']:['webpack','sourcemap']
    },
    webpack:{
      devtool:'cheap-module-eval-source-map',
      resolve:{
         extensions:['','js','jsx'],
         root:path.resolve(__dirname+'./src'),
         alias:{
          'sinon':'sinon/pkg/sinon'
         }
      },
      module:{
        noParse:[
	  /node_modules\/sinon\//
	],
	loaders:[
	  {
	    test:/\.js$/,
	    loaders:['babel'],
	    exclude:/node_modules/
	  }
	]
      }
    },
    externals:{
      'jsdom':'window',
      'cheerio':'window',
      'react/lib/ExecutionEnvironment':true,
      'react/lib/ReactContext':'window'
    },
    webpackMiddleware:{
      noInfo:true
    },
    plugins:[
      'karma-mocha',
      'karma-chai',
      'karma-webpack',
      'karma-phantomjs-launcher',
      'karma-spec-reporter',
      'karma-sourcemap-loader'
    ]
  });
};
